server:
  port: 8080

spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5432/erecruitment_db
    username: postgres
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  sql:
    init:
      mode: never
app:
  jwt:
    secret: 8f6c9b4d2e7a1f5c8b3d6e9a2c4f7b1d8e5a9c2f6b3d7e1a4c8f5b2d9e6a1c7
    expiration: 86400000